# Generated by Django 5.1.3 on 2024-12-01 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "expertId",
                    models.AutoField(
                        db_column="expertId", primary_key=True, serialize=False
                    ),
                ),
                ("expertName", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("companyName", models.CharField(max_length=255)),
                ("introduction", models.TextField()),
                ("estimatedPrice", models.FloatField()),
                ("yearsInService", models.IntegerField()),
                ("numOfEmployees", models.IntegerField()),
                ("businessHours", models.JSONField()),
                ("paymentMethods", models.TextField(blank=True, null=True)),
                ("background", models.TextField(blank=True, null=True)),
                ("similarJobsNearYou", models.IntegerField()),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
            ],
            options={"db_table": '"Expert"', "managed": False,},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "reviewId",
                    models.AutoField(
                        db_column="reviewId", primary_key=True, serialize=False
                    ),
                ),
                ("numOfStars", models.IntegerField(default=5)),
                ("review", models.TextField()),
                ("dateOfReview", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": '"Review"', "managed": False,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userId",
                    models.AutoField(
                        db_column="userId", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(default="user", max_length=50)),
            ],
            options={"db_table": '"User"', "managed": False,},
        ),
    ]
