# Generated by Django 5.1.3 on 2024-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "messageId",
                    models.AutoField(
                        db_column="reviewId", primary_key=True, serialize=False
                    ),
                ),
                ("expertId", models.IntegerField(db_column="expertId")),
                ("userId", models.IntegerField(db_column="userId")),
                ("message", models.TextField()),
                ("role", models.TextField()),
                ("userName", models.CharField(max_length=255)),
                ("expertName", models.CharField(max_length=255)),
            ],
            options={"db_table": '"message"', "managed": False,},
        ),
    ]
